//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курисовик_3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class coffeeEntities : DbContext
    {
        private static coffeeEntities _context;
        public coffeeEntities()
            : base("name=coffeeEntities")
        {
        }
        public static coffeeEntities GetContext()
        {
            if (_context == null)
                _context = new coffeeEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autorization> Autorization { get; set; }
        public virtual DbSet<ingridients> ingridients { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<Structure> Structure { get; set; }
        public virtual DbSet<Type1> Type1 { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
